on:
  release:
    types: [published]
name: Upload Release Asset
jobs:
  release:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build binaries
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o gtestcert -ldflags "-X main.Version=$(git describe --tags)" && tar czf "gtestcert-$(git describe --tags)-linux-amd64.tar.gz" gtestcert
          CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=6 go build -o gtestcert -ldflags "-X main.Version=$(git describe --tags)" && tar czf "gtestcert-$(git describe --tags)-linux-arm.tar.gz" gtestcert
          CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o gtestcert -ldflags "-X main.Version=$(git describe --tags)" && tar czf "gtestcert-$(git describe --tags)-linux-arm64.tar.gz" gtestcert
          CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o gtestcert -ldflags "-X main.Version=$(git describe --tags)" && tar czf "gtestcert-$(git describe --tags)-darwin-amd64.tar.gz" gtestcert
          CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -o gtestcert -ldflags "-X main.Version=$(git describe --tags)" && tar czf "gtestcert-$(git describe --tags)-darwin-arm64.tar.gz" gtestcert
          CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o gtestcert.exe -ldflags "-X main.Version=$(git describe --tags)" && zip -9 "gtestcert-$(git describe --tags)-windows-amd64.zip" gtestcert.exe
          CGO_ENABLED=0 GOOS=windows GOARCH=arm64 go build -o gtestcert.exe -ldflags "-X main.Version=$(git describe --tags)" && zip -9 "gtestcert-$(git describe --tags)-windows-arm64.zip" gtestcert.exe
      - name: Upload release artifacts
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require("fs").promises;
            const { repo: { owner, repo }, sha } = context;

            const release = await github.repos.getReleaseByTag({
              owner, repo,
              tag: process.env.GITHUB_REF.replace("refs/tags/", ""),
            });
            console.log("Release:", { release });

            for (let file of await fs.readdir(".")) {
              if (!file.startsWith("gtestcert-")) continue;
              console.log("Uploading", file);
              await github.repos.uploadReleaseAsset({
                owner, repo,
                release_id: release.data.id,
                name: file,
                data: await fs.readFile(file),
              });
            }
